FROM apache/airflow:2.8.1

# Step 1: Install system packages as root
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    python3-dev \
    libatlas-base-dev \
    libopenblas-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Step 2: Switch to airflow user and install Python packages
USER airflow

RUN pip install --no-cache-dir \
    scikit-learn==1.3.2 \
    pandas \
    pyarrow \
    mlflow
