apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 5050        # Update the port exposed on the service
      targetPort: 5050   # Update the target port inside the container
      nodePort: 30036    # This stays the same (you can change it too if you want a different port)
